function [varargout] = videoTextSmall(string,dim)
% h = videoText(string,dim)
% Writes small left-aligned text at dim = [left bottom width height].
h = annotation('textbox',dim,...
    'string',string,...
    'FontSize',14,...
    'Interpreter','latex',...
    'LineStyle','none',...
    'fitboxtotext','on',...
    'horizontalalignment','left');

if nargout == 1
    varargout{1} = h;
end
end
