function [varargout] = videoTitle(string,dim)
% h = videoTitle(string,dim)
% Writes large centered text at dim = [left bottom width height].
if nargin == 1
    dim = [0 0.9 1 0.1];
end

h = annotation('textbox',dim,...
    'string',string,...
    'FontSize',30,...
    'FontWeight','bold',...
    'Interpreter','latex',...
    'LineStyle','none',...
    'fitboxtotext','on',...
    'horizontalalignment','center');

if nargout == 1
    varargout{1} = h;
end
end
